### ISSUE TITLE
Custom theme for Beagle

### ISSUE THREAD

**Issue by egorikftp** [pandulapeter/beagle#10]
Hello)

I faced with the issue if I set the custom theme for the Beagle library, the theme applies to the whole activity.

```
Beagle.imprint(
    application = application,
    appearance = Appearance(themeResourceId = resourseId)
)
```

Can we fix this behaviour and apply that only for Navigation drawer?

**Comment by pandulapeter** [comment]
Hi!

What you're describing is a bug and unfortunately I'm unable to reproduce it. Could you give some more information about how you're using themes in your app? Is the problem specific to a device / Android version?

Please take a look at how the `example` module does this in (this)[https://github.com/pandulapeter/beagle] repo, you can clone it and check out my implementation that does exactly what you're trying to achieve. What are the differences?

**Comment by egorikftp** [comment]
Ok, I will try to reproduce in the sample)

More info about the bug:
In our production application, we have custom theme with specific colours. In this case, the UI of the Beagle debug menu looks strange) 
After that, we decided to create custom theme for library, but faced with an issue above)

**Comment by pandulapeter** [comment]
Check out the sample, what you need is implemented there and should work :) Let me know if you find out what's wrong!

**Comment by egorikftp** [comment]
Looks like not reproduces in the latest version)

Thank you for support.

**Comment by pandulapeter** [comment]
That's good to hear! Thanks for the update.
