### ISSUE TITLE
On SDK 31 and above the screen recording crashes when started

### ISSUE THREAD

**Issue by stephen-marc** [pandulapeter/beagle#103]
The screen recoding crashes with the following stacktrace:

`java.lang.RuntimeException: Unable to start service com.pandulapeter.beagle.core.util.ScreenCaptureService@3f30fa2 with Intent { cmp=de.vhs.leseapp.debug/com.pandulapeter.beagle.core.util.ScreenCaptureService (has extras) }: java.lang.IllegalArgumentException: de.vhs.leseapp.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                 Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

**Comment by pandulapeter** [comment]
Thank you for finding the crash and for the quick fix! I just released version [2.8.1](https://github.com/pandulapeter/beagle/releases/tag/2.8.1) which contains your changes, it should be available on Maven in the next 15-20 minutes.
