### ISSUE TITLE
Beagle crash logging doesn't work

### ISSUE THREAD

**Issue by Pirokar** [pandulapeter/beagle#105]
Hello!
I have this in my Application class:
`Beagle.initialize(
            this,
            behavior = Behavior(
                bugReportingBehavior = Behavior.BugReportingBehavior(
                    crashLoggers = listOf(BeagleCrashLogger)
                )
            )
        )`
Then in my activity I'm trying to simulate crash:
`arrayListOf("")[5]`
App just crashing, no window showing.

**Comment by Pirokar** [comment]
I tested it in the end of onCreate() on Activity. I've found, that if crash happened some times lated, for example, with
`Handler(Looper.getMainLooper()).postDelayed({
            arrayListOf("")[5]
        }, 1500)`
then window will show. But I think it should work even in the beginning of "onCreate()"

**Comment by pandulapeter** [comment]
Thanks for finding the issue and for the repro steps!

Making the bug reporting activity run in a separate process seems to have fixed the issue.

The new version - [v2.8.2](https://github.com/pandulapeter/beagle/releases/tag/2.8.2) - contains the fix, let me know if you encounter any other problems.
