### ISSUE TITLE
BeagleNetworkInterceptor is misleadingly named

### ISSUE THREAD

**Issue by angusholder** [pandulapeter/beagle#11]
Due to the name I assumed I had to add BeagleNetworkInterceptor using `OkHttpClient.Builder.addNetworkInterceptor()`. This worked fine for a while, until I enabled gzip compression on backend responses, at which point [this line](https://github.com/pandulapeter/beagle/blob/147422fca1987f0de5905c56d02b7aa9c5e2484b/beagle/src/main/java/com/pandulapeter/beagle/BeagleNetworkInterceptor.kt#L75) started quietly mangling all my gzipped responses, then gzip decompression runs _after_ the network interceptors, resulting in some confusing gzip decoding error.

I wonder if there's any way to assert that BeagleNetworkInterceptor got added as a normal interceptor and not a network interceptor, so this bug could've been caught early?

**Comment by pandulapeter** [comment]
Sorry to hear about that, I hope you didn't spend too much time debugging before figuring out it wasn't your fault. I can change the name of the class in the next update and improve the documentation to avoid confusions.

Just to be clear: did using `addInterceptor()` instead of `addNetworkInterceptor()` fix your issue? If not, do you have any suggestions of what I should change to not mess up the compression?

**Comment by angusholder** [comment]
No worries, I didn't mean it to come across as pointing blame!

Yeah `addInterceptor` fixed it. I suppose this is more of an OkHttp problem, it can be easy to mix up which kind of interceptor you have, and it will mostly work when you do it wrong, just ends up being hard to debug 💀 

I think BeagleNetworkInterceptor _could_ be adjusted to take the `Content-Encoding: gzip` header into account, but I don't know if it would be worthwhile, there might be other ways in which it doesn't work properly when inserted as a network interceptor, probably better just to document clearly which kind of interceptor it is.

Thanks for the quick reply!

**Comment by pandulapeter** [comment]
Thanks for raising the issue I'll look into it!

**Comment by pandulapeter** [comment]
In v2 the interceptor is accessed using Beagle.interceptor and the KDoc for the relevant class also contains a code snippet., so hopefully there will be no more confusion.
