### ISSUE TITLE
Double debug-panel

### ISSUE THREAD

**Issue by l1onPro** [pandulapeter/beagle#116]
when i try to open a new activity, it opens 1 more panel on top of another

**Comment by l1onPro** [comment]
**_Steps:_**
1. Open debug panel
2. click `TextModule`:
- `Beagle.hide()`
- `startActivity()`
3. Opened new activity

**_Result:_** Opened new activity with debug panel. 
**_Waiting:_** Opened new activity without debug panel. 

---
**_Steps:_**
1. Open debug panel
2. click `TextModule`:
- `Beagle.hide()`
- `startActivity()`
3. Opened new activity
4.  `Beagle.hide()` in `onCreate()` activity 

**_Result:_** Opened new activity with debug panel. 
**_Waiting:_** Opened new activity without debug panel.

**Comment by pandulapeter** [comment]
Beagle adds itself to every activity and tries to preserve its state. If you open a new activity with Beagle opened, it will try to stay opened. Maybe you could do something like this in your Text module's click listener:

```
Beagle.performOnHide { openActivity() }
Beagle.hide()
```

But yeah, something fishy is going on here, let me investigate your original issue.

**Comment by pandulapeter** [comment]
Should be fixed in [2.9.1](https://github.com/pandulapeter/beagle/releases)
