### ISSUE TITLE
Beagle don't work if app has different brands

### ISSUE THREAD

**Issue by egorikftp** [pandulapeter/beagle#13]
Hi)

In our application we have different brands and we override applicationId in gradle

```
 productFlavors {

   main {
        applicationId "com.test.mainapp"
   }

   brand {
        applicationId "com.test.brandapp"
   }
}
```

I guess, this new line broke initialization

https://github.com/pandulapeter/beagle/compare/1.4.3...1.4.4#diff-8453b0883139ceae004ef769881c96edR227

PS. As idea, maybe better to make a method `Beagle.addExcludes(var args)`

**Comment by pandulapeter** [comment]
Thanks a lot for reporting this! Sorry about that breaking change.

I've just created a new release (v1.4.6) that adds an optional `packageName` parameter to the Beagle.imprint() function which you can use to specify the core package name of your Activity classes. Hopefully this fixes the issue.

Let me know if it works!

**Comment by egorikftp** [comment]
Great job)
Works as expected)

**Comment by pandulapeter** [comment]
Awesome! Thanks again, feel free to open new issues if you find anything else in the future
