### ISSUE TITLE
Gesture navigation problem OnePlus.

### ISSUE THREAD

**Issue by gelly9** [pandulapeter/beagle#14]
Unfortunately on Android 10 on OnePlus, the new gesture navigation conflicts with the Beagle drawer open action. Can you add some other trigger to open the drawer?

**Comment by pandulapeter** [comment]
The shake-to-open feature was just added in v1.5.0 through [TriggerGestures](https://github.com/pandulapeter/beagle/blob/master/beagle-core/src/main/java/com/pandulapeter/beagleCore/configuration/TriggerGesture.kt) specified when initializing the library.
