### ISSUE TITLE
requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by Shusshu** [pandulapeter/beagle#2]
Do you have a solution when we explicitly uses `requestFeature(Window.FEATURE_CONTENT_TRANSITIONS)` before setContentView ?

**Comment by pandulapeter** [comment]
Apparently the way Beagle modifies the content view (which happens in through the ActivityLifecycleCallbacks set on the Application instance) resets the theme.

Please try setting "windowContentTransitions" true for the theme you provide in Beagle.initialize() / Beagle.imprint() and see if it fixes the issue.

**Comment by Shusshu** [comment]
It's already to true
the problem is I cannot use requestFeature

**Comment by pandulapeter** [comment]
Cannot reproduce, looks like an edge-case.
