### ISSUE TITLE
BeagleNetworkInterceptor has private access when calling from Java

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#25]
<img width="645" alt="Screen Shot 2020-04-18 at 11 22 34 AM" src="https://user-images.githubusercontent.com/7057959/79627987-098be880-8167-11ea-90cb-910c5d5e17e4.png">

**Comment by mochadwi** [comment]
Solved:

`.addInterceptor(BeagleNetworkInterceptor.INSTANCE)`

**Comment by pandulapeter** [comment]
That's right, accessing Kotlin singletons from Java glad you found the solution. I haven't really tested interoperability with Java so let me know if you face any issues!
