### ISSUE TITLE
EditText equivalent Trick

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#29]
Does beagle have `EditText` equivalent for Trick or modules to include that will 

Similar like `SingleSelectionList`, `SimpleList` but with additional features:

1. input some text
1. able to have an action with the provided text

**Comment by pandulapeter** [comment]
Hi! This will definitely be part of v2.0 - I'm planning to finalize that during next week. It will probably be a button that triggers a dialog with an EditText where the input can be edited. I'll keep this issue open to let you know when it's ready to be used :)

**Comment by pandulapeter** [comment]
Better late than never: TextInputModule is now added in version 2.0.0-beta01.
