### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewTreeViewModelStoreOwner;

### ISSUE THREAD

**Issue by TooLazyy** [pandulapeter/beagle#30]
Getting such an error from start.
Version - 2.0.0-beta05.
Have no idea what library I should add to make it works.

**Comment by pandulapeter** [comment]
Hi! Thanks for letting me know, that's very weird...

Could you maybe try adding this to your dependencies:

`implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"`

Anyway, the library should come with all the dependencies it needs so I'd suspect some edge-case issue. Try doing an invalidate caches / Restart in Android Studio. Also.. if you clone this repository, can you run the example app?

**Comment by pandulapeter** [comment]
Wait a second... The class you mentioned is used in AppCompatActivity. Is it possible that you're using an outdated appcompat? Just to figure things out, could you please try to update to this version:

`implementation "androidx.appcompat:appcompat:1.3.0-alpha01"`

**Comment by TooLazyy** [comment]
Yeah. Seems like appCompat version is the point.
And I strongly don't recommend to use alpha versions of libraries, as they are not stable. Beta may be, but not alpha.
Solution - I had to force the stable appCompat version.

**Comment by pandulapeter** [comment]
Glad you found the solution!

You're definitely right about not depending on alpha versions, I'll downgrade everything to stable in the next update (should not affect any functionality)... I'll keep this open until the next release is ready, let me know if you encounter any other issues!

**Comment by pandulapeter** [comment]
Theoretically fixed in release [2.0.0-beta06](https://github.com/pandulapeter/beagle/releases/tag/2.0.0-beta06). Now all dependencies are stable versions, in the case of app compat it's 1.1.0.
