### ISSUE TITLE
[Feature Request] Separate logging from Android module

### ISSUE THREAD

**Issue by fknives** [pandulapeter/beagle#34]
It would be nice if the Logging and NetworkLogging options could be included as java modules:
For multi-module projects where the networking layer is separated from the android-ui layer, either for separation of concerns or reusability, at the moment the main module most know about okhttp in order to provide the interceptor to the networking layer. Ofc this solution works, but it adds an okhttp dependency into the ui module while it shouldn't know anything about networking.

so the idea would be let's say we have a *network-layer* module:
this includes a beagle-network-loging dependency or something similar
the *app* module includes beagle the same way as does it now
The *network-layer* module could provide a BeagleNetworkLogger or something similar which can be added to Beagle itself, and gets the data from the already created interceptor.

This way the *app* module would not know anything about the networking only that there is a logger it should include, while network logging is still available.
Ofc names and the solution can be changed simplified, this just tries to illustrate the use-case and some rough high-level version of the problem.

**Comment by pandulapeter** [comment]
One of the core values I wanted to keep is simplicity: Beagle should be easy to integrate and setup. The current architecture works fine for simple projects and, while still usable on larger ones, I agree that it should not break the separation of concerns principle of a well tought-out app. But we should find a compromise that keeps the library accessible to beginners as well.

The more I think about this the more roadblocks I see. Just for the sake of brainstorming, let me summarize the issue:

 - The solution you hinted at would be to split some of the Modules into separate libraries. This would mean that for example the NetworkLogListModule or the LogListModule would come as separate dependencies (two for each, as we need the `noop` variants as well). This is something I'd be more or less comfortable with from the API perspective as it's doable with the current setup (anybody can write custom Modules: they don't have to be bundled with Beagle) and this granular approach would open up the possibility to add more, heavy Modules (for example a Ktor logger, as now we only have OkHttp). It would become a bit more cumbersome to integrate but I think that's still easy enough to understand and definitely a nicer solution than including a huge library with many things that aren't going to be used by most people.
- The problem with this is that to write a custom [Beagle Module](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/contracts/module/Module.kt), we would need to implement interfaces from the `common` module. However, a Module is expected to provide its own UI as well (see [Cell](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/contracts/module/Cell.kt) and [ViewHolder](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/contracts/module/ViewHolder.kt)), which, at the lowest level means extending RecyclerView ViewHolders. So I can't think of a nice way to do this in a pure Kotlin module, that does not depend on the Android SDK.

So I think the first thing we should figure out is how to make `common` not depend on Android. But even in that case, adding a NetworkLogListModule would mean at least 4 lines of Gradle dependencies (`normal` and `noop` in your project's core module as well as 2 in the app module to make the connection to Beagle), besides the minimum 2 lines needed in the app for Beagle (`normal` and `noop`). And this would become more complex the more modules we cut out from the main library. So at this point I think we're starting to have issues with how easy-to-use the library is.

All in all, I'm 100% a fan of the idea but we need to figure out the implementation. For the time being, functionality problems can be resolved with interfaces, but your main concern with the `app` module knowing about things it shouldn't is valid.

**Comment by pandulapeter** [comment]
One way that might be doable is to create and abstraction for logging, as (I think) everything that might belong to a pure Kotlin dependency has to do with logs. This would mean that the actual NetworkLogListModule or LogListModule would remain part of Beagle, but they would only work after a separate dependency is added to the core module and connected somehow. So we could create a separate Module type that consumes Logs through an interface, no metter what kind of logs they are (simple logs, requests intercepted from OkHttp or Ktor, etc).

**Comment by pandulapeter** [comment]
I've managed to unbundle the logging functionality from the main library in v2.0.0-beta08. Check out [this part of the readme](https://github.com/pandulapeter/beagle#intercepting-network-events) for migration steps, I still have some testing to do but theoretically we can now use these features in pure Kotlin / Java modules.
