### ISSUE TITLE
Refactor inset handling

### ISSUE THREAD

**Issue by pandulapeter** [pandulapeter/beagle#37]
Now that we target SDK 30 the current inset handling logic is deprecated. It also didn't work well on some apps (especially with the Insetter library it needed some manual workarounds) so hopefully migrating to new API-s will fix the issues.

**Comment by pandulapeter** [comment]
Blocked by appCompat: the necessary methods are not yet part of the stable release, so this can only be implemented after 1.3.0 comes out.

**Comment by rahulsainani** [comment]
Hey @pandulapeter I have been using this library and it's been very helpful, thank you! I have some changes locally, to use the new WindowInsetsCompat API with inset types in `DebugMenuDrawerLayout`, `DebugMenuActivity`, `DebugMenuBottomSheet` and `DebugMenuDialog`. No implementation changes, just mapping `androix.core.graphics.Insets` to `com.pandulapeter.beagle.common.configuration.Insets` to avoid any breaking changes of users. I can make the PR, just let me know. :)

**Comment by pandulapeter** [comment]
Hi @rahulsainani ! I'm very happy to accept any contributions, feel free to create a PR and I'll do some testing next week. If everything goes well, it will be part of the next release (with the regular dependency updates). Let me know if you need help, thanks in advance!

**Comment by rahulsainani** [comment]
Sounds good! 👍 Just created a PR, please take a look. Happy to do any changes if required.

**Comment by pandulapeter** [comment]
@rahulsainani looks like the artifacts for release[2.6.5](https://github.com/pandulapeter/beagle/releases/tag/2.6.5) are live, thanks again for the help!

**Comment by rahulsainani** [comment]
@pandulapeter glad to help! Thanks for the quick review and release! 👍
