### ISSUE TITLE
Rewrite the dialog used for displaying network request / response payloads

### ISSUE THREAD

**Issue by pandulapeter** [pandulapeter/beagle#38]
Required features:
- Formatting the JSON should be done in the background to avoid blocking the UI thread in case of large payloads.
- Controls for showing request / response metadata (headers, timestamp, duration) should be on the UI.
- The copy feature is currently based on Android's default text selection UX which is cumbersome with JSON-s.
- Expanding / collapsing JSON objects / arrays would be very helpful.
- Links should be clickable.
- Scrollbars are also needed.

**Comment by pandulapeter** [comment]
Some of these improvements were implemented in [v2.0.2](https://github.com/pandulapeter/beagle/releases/tag/2.0.2).

**Comment by percula** [comment]
Thanks for this amazing library! Can you please add the ability to share **all** network activity? This would be particularly useful for communicating with QA engineers who might not know which specific network call is the problem.

**Comment by pandulapeter** [comment]
Great idea, thanks! I'm working on a [separate module](https://github.com/pandulapeter/beagle/issues/24) which will bring up a bug reporting UI, where QA engineers can select attachments to add to the bug report, such as screenshots, logs, or, as you mentioned, network activity logs. I have to find a good way that works for any app (probably file attachments as the clipboard has a size limitation). So this might take a few weeks, but it's definitely on the TODO list!

**Comment by pandulapeter** [comment]
Closing this as [release 2.1.2](https://github.com/pandulapeter/beagle/releases/tag/2.1.1) introduced a file-based sharing solution which solves most of the issues (expand - collapse directly in the dialog feels like an overkill for now). The ability to share multiple network logs will be part of the BugReportModule which is being worked on on a separate branch.

**Comment by pandulapeter** [comment]
@percula Release [2.2.0](https://github.com/pandulapeter/beagle/releases/tag/2.2.0) introduces the [BugReportButtonModule](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/BugReportButtonModule.kt) which can be used for sending multiple log files, even all of them. Check it out if you're still interested :) It should open a screen that looks something like this:

![bugReport](https://user-images.githubusercontent.com/10262638/96491508-01fae880-124b-11eb-9e98-0c071663e628.jpg)

**Comment by percula** [comment]
@pandulapeter Wonderful! I'll definitely be adding this. Thanks!
