### ISSUE TITLE
Overlay is messing up with Layout Inspector

### ISSUE THREAD

**Issue by jakoss** [pandulapeter/beagle#59]
Hi,

Overlay is making work with Layout Inspector quite hard. Since it's always on top - it's hard to select ui item under it. Have you considered making overlay optional or even making a switch for it directly in beagle? I understand that without that screenshot/recording wouldn't work?

**Comment by pandulapeter** [comment]
Thanks for letting me know, I rarely use the Inspector so I didn't notice this problem. I'll see what I can do but it's not an easy fix, the overlay is also needed for the DrawerLayout to work (the library doesn't touch the app's layouts, it just adds a Fragment on top which, in case of the drawer, needs to have two children: overlay + the debug menu itself). No promises yet but I'll look into it.

**Comment by pandulapeter** [comment]
Good news, there's a simple workaround! Just select the DebugMenuDrawerLayout from the component tree, right click and press "Hide subtree". This will make the overlay disappear and everything behind it becomes selectable.

<img width="623" alt="layoutInspector" src="https://user-images.githubusercontent.com/10262638/96709273-2538ab80-13a3-11eb-814c-ac368e9f0550.png">

**Comment by jakoss** [comment]
Awesome, thanks
