### ISSUE TITLE
[Feature Request] Crash screen & OkHttp Replay

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#60]
I cannot find any docs regarding both the ability to captured runtime crash and Okhttp replay. CMIIW

References library:

1. https://github.com/mlegy/red-screen-of-death (very similar to the one in Flutter)
1. ~https://github.com/airbnb/okreplay (for e2e testing/would be great if QA/Dev can replay a set of okhttp replay, like [time-travel debug mode](https://github.com/arkivanov/MVIKotlin#watch-video-time-travel-logs-debug-etc))~ (needs a lot of efforts building this)

**Comment by pandulapeter** [comment]
Great ideas! The first one is definitely be doable with an UncaughtExceptionHandler, I'll just have to make sure not to mess up the crash reporting of other services like Crashlytics and to generate stack traces that can be later attached on the Bug Report screen. So, coming soon.

As for the second one, it's an interesting concept I wasn't familiar with, but it looks like a bigger effort, and I'll probably won't be able to do it on the same quality as AirBnb. So an integration with that library would probably be a better approach, just making sure that there aren't compatibility issues.

**Comment by mochadwi** [comment]
Thanks for the answer, agreed I'm just wondering if both the above library is already in the milestone or not. As for the second I also agreed this is need bigger effort, we would use the airbnb one then in our apps :)

**Comment by mochadwi** [comment]
For the first one, it's a good combination with your screenshot features, after our apps crash QA can also attached the stacktrace.

But as for now, thus the stacktrace already included in `LogListModule` you've built or maybe a reference to insert (manually on our apps) with stacktrace included in the `.zip` files for `BugReportButtonModule` before sharing?

**Comment by pandulapeter** [comment]
Right now the limitation of the bug reporting feature is that it can only attach logs from the current session (logs are stored in the memory, they are only written to files when the user tries to share them). So yeah, I should save the stack trace and the last few logs into a file so that QA can create bug reports with them even after an app restart.

**Comment by mochadwi** [comment]
> Right now the limitation of the bug reporting feature is that it can only attach logs from the current session (logs are stored in the memory, they are only written to files when the user tries to share them). So yeah, I should save the stack trace and the last few logs into a file so that QA can create bug reports with them even after an app restart.

that would be awesome, thanks for considering this feature and the latter for red screen of death!

**Comment by pandulapeter** [comment]
Added in [release v2.3.0](https://github.com/pandulapeter/beagle/releases/tag/2.3.0). Beagle now automatically catches unhandled exceptions, displays the stack trace in a dialog, and opens the bug reporting screen so that it can be attached. It also introduces the "isPersisted" parameter to the Beagle.log() / BeagleLogger.log() functions, which can be used to persist log messages on the local storage.

**Comment by jakoss** [comment]
@pandulapeter do you have plans to call previously set default handler exception? It's really easy, just store current handler somewhere and call it every time you get a exception. This way you can have bug screen and send information to crashlytics (for example). I'm releasing beagle to qa team, so current implementation just don't work for me

**Comment by pandulapeter** [comment]
@jakoss That's a bit awkward, I didn't realize that I can do that :))) Thanks for the tip, I'll look into it for the next update. Until that, you can completely disable this new feature:

```Beagle.initialize(
    application = this,
    ...,
    behavior = Behavior(
        bugReportingBehavior = Behavior.BugReportingBehavior(
            shouldCatchExceptions = BuildConfig.DEBUG // Only enable for build types where Crashlytics is not present!
            ...
            }
        )
    )
)```

If you set shouldCatchExceptions to false, the library should not override the default handler.

**Comment by pandulapeter** [comment]
@jakoss There is a new release ([2.3.1](https://github.com/pandulapeter/beagle/releases/tag/2.3.1)) that should include [this change](https://github.com/pandulapeter/beagle/commit/f013fd74599f6d0bc9a204c523ca41fef051a335). The main problem was that I didn't want the system's default exception handler to kick in: on some Android versions it brings up a dialog  after a few tries ("The app keeps stopping") that blocks the Bug Report screen. On the other hand, exception handlers set by crash reporting libraries should be called, as you pointed out. I eventually had to do string matching based on the package name, hopefully it will work - it needs to be tested a bit more.

**Comment by jakoss** [comment]
I'm happy to test this out :)

**Comment by pandulapeter** [comment]
Looks like it won't work on minified builds anyways :| I opened a [new issue](https://github.com/pandulapeter/beagle/issues/63).
