### ISSUE TITLE
Dynamic list

### ISSUE THREAD

**Issue by alexKatona** [pandulapeter/beagle#61]
Hello I was using your library for some time, its great so far, but havent figured out how to create a listItemModule with dynamic data. For example I want to create a custom analytics list where I would log all my events to easily check which one was called.

**Comment by pandulapeter** [comment]
Hi! Two things, the first one to answer your question, the second one to offer an alternative approach.

1) To add an [ItemListModule](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/ItemListModule.kt) to your debug menu, first you need to create a data class that represents a single element, by implementing the [BeagleListItemContract](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/contracts/BeagleListItemContract.kt) interface. For example:

```
data class AnalyticsEvent(
    val eventName: String
) : BeagleListItemContract {

    override val id: String = eventName // Needs to be unique
    override val title: Text = eventName.toText() // This appears on the UI
}
```

After that, you can instantiate the module in a way that it will be generic to `AnalyticsEvent`:

```
Beagle.add(
    ItemListModule<AnalyticsEvent>(
        title = "Analytics events",
        items = listOf<AnalyticsEvent>(
            AnalyticsEvent("event1"),
            AnalyticsEvent("event2"),
            AnalyticsEvent("event3")
        ),
        id = "ANALYTICS",
        onItemSelected = { analyticsEvent ->
            Log.d("tag", "The user clicked on the ${analyticsEvent.eventName} item.")
        }
    )
)
```
Specifying the `id` parameter above is optional, however, it's useful if you want to update the contents. Now that we have a non-random value, every time you call `Beagle.add()` with a module that has the id `"ANALYTICS"`, it will replace the already existing one. This would be one way to update your list. However...

2) If I understand you correctly, you want to track the analytics events on the UI. There's a much simpler way to do that! Simply use Beagle to log every analytics call under the same label, like this:

```
Beagle.log(
    message = "The event you want to track",
    label = "ANALYTICS_LABEL",
    payload = "Optional payload data for the event"
)
```

With this setup, all you need to do is add an instance of [LogListModule](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/LogListModule.kt) to the debug menu, which will be filtered only for the `"ANALYTICS_LABEL"` label:

```
Beagle.add(
    LogListModule(
        label = "ANALYTICS_LABEL",
        title = "Analytics events".toText()
    )
)
```

This list will automatically update whenever a new event is logged and you can also tap on the items to open a detail dialog which contains the payload and the option to generate a shareable txt file.


Let me know if any of these helps or if you have any other questions. I understand that the API is not very intuitive in some cases, so let me suggest going through [the showcase app](https://play.google.com/store/apps/details?id=com.pandulapeter.beagle), as it contains examples and code snippets for most use cases.

**Comment by alexKatona** [comment]
Hi there, thanks for the blazing fast response,

the second approach looks very good, I already tried it and I will use that one since its a simple solution to my feature.

Thank you :+1:
