### ISSUE TITLE
Is there way to persist value of TextInputModule on SharedPreference with a specific key?

### ISSUE THREAD

**Issue by maxfie1d** [pandulapeter/beagle#65]

**Comment by pandulapeter** [comment]
Hi!

When you instantiate a `TextInputModule`, there is the optional parameter called `isValuePersisted` (which is false by default). To enable saving and restoring to / from SharedPreferences, simpy set this value to `true`, AND set a unique, constant `id` for the module (again, in its constructor - by default the `id` is random). This `id` will be the key used in shared preferences, prefixed with "string_" in this case (Beagle creates a shared preferences file called "beagle").

You can have the same functionality for `CheckBoxModule`, `SwitchModule`, `SliderModule`, `SingleSelectionListModule`, and `MultipleSelectionListModule` as well.

Let me know if you have any other questions or feel free to close this if this helped :)

**Comment by maxfie1d** [comment]
Nice, it worked 🎉 

Thank you.
