### ISSUE TITLE
Statusbar color regression in 2.3.8

### ISSUE THREAD

**Issue by jakoss** [pandulapeter/beagle#68]
After upgrading beagle to 2.3.8 the status bar in whole app was set up to white color, it seems like you're rewriting theme values?

**Comment by pandulapeter** [comment]
Definitely not, I'd suspect a library version conflict instead. Check out [this file](https://github.com/pandulapeter/beagle/blob/master/build.gradle) to see what versions of third party libraries are included with Beagle, should be the latest stable version from everything.

Could you maybe send a screenshot just of the status bar? It's either this library problem, or maybe Beagle ruins your inset handling logic (it shouldn't... but just want to make sure). Are you using `windowLightStatusBar` in your theme?

**Comment by jakoss** [comment]
I'm just setting up <item name="colorPrimaryDark">@color/colorPrimaryDark</item> in styles.

With 2.3.8:
![image](https://user-images.githubusercontent.com/3933348/99551757-86609880-29bc-11eb-9709-2b15d44159a3.png)

With 2.3.7 (expected result):
![image](https://user-images.githubusercontent.com/3933348/99551938-bad45480-29bc-11eb-8046-57f8dae3250c.png)

**Comment by pandulapeter** [comment]
Thanks for the screenshots! I'm still trying to think of ways how any of the changes could have caused this... Just to make sure, if you replace in gradle this line:

```debugImplementation "com.github.pandulapeter.beagle:ui-drawer:$beagleVersion"```

with this line:

```debugImplementation "com.github.pandulapeter.beagle:noop:$beagleVersion"```

will the issue be present?

**Comment by jakoss** [comment]
With noop version it's working fine

**Comment by pandulapeter** [comment]
Okay, then it must be my fault somehow... I'll look into it and keep you updated, sorry for the inconvenience and thanks for reporting the issue!

**Comment by pandulapeter** [comment]
Found it: looks like DrawerLayout has some sort of internal inset handling which I have accidentally overridden. I managed to reproduce your issue and it should be fixed in the [new release, v2.3.9](https://github.com/pandulapeter/beagle/releases/tag/2.3.9). However, the issue will remain open until you confirm the fix :)

**Comment by jakoss** [comment]
I cannot download this version, on Jitpack it looks like build failed

**Comment by pandulapeter** [comment]
Had to restart it a couple of times, something timed out :| Could you give it a try now? It should be working.

**Comment by jakoss** [comment]
Working great now, thanks!
