### ISSUE TITLE
Separate process for beagle causing some commotion

### ISSUE THREAD

**Issue by jakoss** [pandulapeter/beagle#69]
I'm wondering if using separate process for beagle exception handler is really necessary? I had a small but really annoying issue with "run" tab in android studio and i just discovered what is causing it.

On this tab (as well as in debug tab) logcat for process should be captured (this can be even configured with "Logcat output" section of the "Debugger" settings page. But, unfortunetely, it seems like android studio cannot decide which process to choose in logcat capturing and.. does not capture anything. Basically - if app spawns multiple processes the logcat won't get captured into run/debug tab and we need to use logcat tab directly. It seems minor, but it was driving me crazy for a few weeks and i was sure that was due to some bug in android studio 4.1 ;)

Now, i understand why you are doing this. This is to make sure that bug report activity will get displayed on crash. But i'm wondering if maybe you could save that info and display it after app restart? There is even api to detect crash reason, but only for api level 30 - https://developer.android.com/reference/android/app/ApplicationExitInfo

**Comment by pandulapeter** [comment]
There should be a way to select the process for which logcat is showing the logs in the IDE but I'm sorry you had this issue, it must have been annoying :| To be honest the entire exception handling right now is a bit of a mess: it doesn't play nice with Crashlytics and even on its own its unreliable, I had some crashes that were not logged at all.

I'd like to have something that works on all supported API levels but the current implementation has too many side effects / quirks. In the next release I'll decouple it from the library: it's going to be a separate dependency to make sure it doesn't mess up things for people who only want the debug menu.

**Comment by jakoss** [comment]
Separating this is a good move. For exception handling you could look at https://github.com/MindorksOpenSource/CrashReporter . I'm using it for a year now and it seems reasonably reliable

**Comment by pandulapeter** [comment]
With [release 2.4.0](https://github.com/pandulapeter/beagle/releases/tag/2.4.0) the crash reporting is now decoupled, no exception handling is done without a [separate dependency](https://github.com/pandulapeter/beagle#displaying-crash-logs). Thanks for the link, that library looks pretty good :) I'll look into it more when I have the time, but it would be really cool to have it working together with Beagle - as both implementations seem to forward the exception to the previously set exception handler, in theory it should be possible.
