### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [pandulapeter/beagle#72]
The markup version of the readme that is displayed for the main page in this repo contains the following bad links:

Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/configuration/Appearance.kt
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/configuration/Behavior.kt
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/tree/master/common/src/main/java/com/pandulapeter/beagle/modules/LogListModule.kt
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/tree/master/common/src/main/java/com/pandulapeter/beagle/modules/NetworkLogListModule.kt
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/common/contracts/BeagleContract.kt
Status code [404:NotFound] - Link: https://github.com/pandulapeter/beagle/tree/master/common/src/main/java/com/pandulapeter/beagle/modules

(The link in the readme’s raw markdown may appear in a different relative format to the link above)

--

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fpandulapeter%2fbeagle
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=pandulapeter

Theses bad links were found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by pandulapeter** [comment]
What a super helpful tool, thanks a lot! Broken links fixed, repository starred 👍
