### ISSUE TITLE
Report a bug, add all logs

### ISSUE THREAD

**Issue by alexKatona** [pandulapeter/beagle#76]
Hello, I am wondering if it would be easily possible to attach all logs during report a bug using a  BugReportButtonModule(). It seems annoying to click on all the checkboxes.

**Comment by pandulapeter** [comment]
Hi! Thanks for the suggestion, I'll include an optional "Attach all" button in the next release.

**Comment by alexKatona** [comment]
Thanks, @pandulapeter 
Maybe a better solution would be to expose a method like BeagleLog#getLogs(label) 
For example I am logging all the analaytics logs with 1 label, and if the QAs find a bug with analytics (wrong name, twice logged etc) it would be more convinient to send only those. I can also Imagine a button in the beagle menu like sendLogsButtons that would show a dialog with list of labels so I can choose which one to send, or all. That dialog is ofc easily doable on the app side if the getLogs would be accessible

**Comment by pandulapeter** [comment]
I added the "Select all" button to the Bug report page section headers in release [v2.4.4](https://github.com/pandulapeter/beagle/releases/tag/2.4.4).

I also very much agree with your idea about exposing the `getLogs()` method for public usage, but this will require some  more refactoring - I'm leaving this issue open until the next release. It will be resolved ASAP.

However, please note that some of what you require is already possible to do. You can create different sections of logs in the Bug reporting screen, filtered by label. To achive this, you'll need something like the following when initializing the library:

```
Beagle.initialize(
    application = this,
    behavior = Behavior(
        bugReportingBehavior = Behavior.BugReportingBehavior(
            logLabelSectionsToShow = listOf("label1", "label2", null), // null will create a section without filtering
            buildInformation = {
                listOf(
                    "Version name".toText() to BuildConfig.VERSION_NAME,
                    "Version code".toText() to BuildConfig.VERSION_CODE.toString(),
                    "Application ID".toText() to BuildConfig.APPLICATION_ID
                )
            }
        )
    )
)
```
Let me know if you give this a try, it should work but it's not a very well tested part of the library.

**Comment by alexKatona** [comment]
Thanks @pandulapeter,
I just tried the behaviour you posted, its working pretty well so basically i could fullfill the requirements to have separate logs and an ability to share then separatelly.

One Minor thing i noticed, IT would be cool to copy text on long Press in the simple lists and maybe in the dialogs showing detail of an entry. For example to copy and paste it in the app etc.

**Comment by pandulapeter** [comment]
Glad to hear that it's working!

As for copy-paste: some older versions of the library used to have this feature (implemented with `android:testIsSelectable="true"`) but it didn't play nicely with the 2D scroll behavior we have for JSON-s for example. I will look into it again but right now the best alternative is the Share button on the top right corner of the dialog (you should be able to "share" to the clipboard). I know that's not exactly what you had in mind, but the text selection UX was really bad, barely usable.

I recently found out about Hyperion - very cool library! It's less customizable than Beagle but easier to set up. And as you mentioned it has some really powerfull tools. I might decide to steal a few ideas but I don't want to spend too much effort duplicating functionality from Android Studio (the Layout inspector is pretty good, there's no chance that I could do something better than that 😄 )

**Comment by alexKatona** [comment]
I get the point with the selectable stuff and aggree, its not worth if its creating issues. I am on android 11 and there is actually no option to share it to clipBoard since when I share it, I think the logs are in .txt even if I click on a specific log item and share it. Maybe a second button next to the share icon in the dialog to copy to clipboard ?

**Comment by pandulapeter** [comment]
Oh you're right, that option is no longer there since we moved on to generate files. And the reason for generating files was that sharing the raw text didn't work for large payloads. Anyway, the separate button is probably the easiest / best idea, it might not work for very long texts but I'll look into it for the next release.

**Comment by pandulapeter** [comment]
Release [v2.5.0](https://github.com/pandulapeter/beagle/releases/tag/2.5.0) introduces a few new public suspend functions: `getLogEntries()`, `getNetworkLogEntries()`, `getLifecycleLogEntries()` and `getCrashLogEntries()`.
