### ISSUE TITLE
beagle network log Chucker-like

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#81]
1. ability to share with same format like chuck: Share as Text, Share as Command & Share as File
2. ability to search word inside request & response (to debug key-value from server response exist)

https://github.com/ChuckerTeam/chucker/

Is it possible to extend current NetworkModule to achieve Chucker-like network logger? Currently we want to move our development solutions to use beagle, but looks like the above features still missing (or maybe in milestone?) from beagle

**Comment by pandulapeter** [comment]
Hey,

Thanks for the suggestions! I'm not going to close this for now, as the requests are valid, but I don't think I'll implement them in the near future. Chucker is a much more specialized tool and it's fair that it has better support for these needs.

1. **Share as Text** - Beagle used to have this but after testing with large payloads, I ran into issues (the clipboard has a limitation for the text size and many apps like Slack simply didn't handle the Intent properly if the String was too long). So right now we only have **Share as File** which should work properly. The JSON in the exported file is indented / formatted. I'm not sure what **Share as Command** means, I'll have to look into it.
2. For now this is only possible if you share the JSON as a file first and then open it in another app. I might add a search box to the dialog in the future, but I'm just reluctant to make that piece of UI even more crowded + opening the keyboard while the app is in the background might have side effects in certain apps.

Anyway, I'll give it some more thought. From the consumer side there isn't really a good way to add these features: you can call `Beagle.getNetworkLogEntries()` and display the results with your own UI, or there's the `Beagle.addNetworkLogListener()` functionality that allows for callbacks. But the only way to improve the dialog itself is to submit a PR to this project (or fork your own version).

**Comment by mochadwi** [comment]
My bad, I mean **Share as Curl Command**, so Backend engineer able to import the raw text into Postman/Insomnia (or any tools the preferred) 


Thanks for pointing out and answering this, agreed Chucker is exist way than before and have a lot of contributors even until now

**Comment by pandulapeter** [comment]
In [release 2.6.0](https://github.com/pandulapeter/beagle/releases/tag/2.6.0) there's a new feature you suggested: the network log dialog now has a search button.

JSON lines matching the query will be highlighted automatically, with the matching substring being underlined. The number of matches near the input field is clickable: every click scrolls to the next line that contains results.

![search](https://user-images.githubusercontent.com/10262638/114270005-b31c5780-9a12-11eb-8bf9-61e8ef8f7d96.png)

I think it's a pretty useful addition, so thanks for the idea. However, if you don't mind, I'll close this issue as I don't plan to address the other point you brought up.

**Comment by mochadwi** [comment]
This is more than enough to migrate our debug solution to use Beagle only :))) really appreciate for your time, energy and efforts!
