### ISSUE TITLE
Jetpack Compose projects unable to click if calling `Beagle.imprint`

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#88]
This is our internal/private project, will try to create new or simple project for this case and update this issue hopefully to try/clone as a reproducible samples 🙏 

Context:

When trying to call the `Beagle.imprint` (we're still using Beagle v1.x) the **_Jetpack Compose_** click handler gone (unable to click any composable functions)

```kotlin
    Beagle.imprint(
        application = this,
        appearance = Appearance(
            themeResourceId = R.style.AppTheme
        ),
        behavior = Behavior(
            shouldResetPendingChangesOnClose = true
        )
    )
```

Commenting out the above code, as workaround to make our composable function able to click, in exchange to prevent beagle to be shown :( 

Information:

```
Compose: 1.0.1
Kotlin: 1.5.21
AGP: 4.2.2
Gradle: 7.1.1
IntelliJ IDEA 2021.2.1 RC (Community Edition)
Build #IC-212.5080.39, built on August 19, 2021
Runtime version: 11.0.11+9-b1504.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: com.codestream.jetbrains-codestream (11.0.12+180)
Kotlin: 212-1.5.10-release-IJ5080.39
```

**Comment by mochadwi** [comment]
reproducible samples: 
[android-agentapp-min.zip](https://github.com/pandulapeter/beagle/files/7042160/android-agentapp-min.zip) @pandulapeter

**Comment by mochadwi** [comment]
will try to update the beagle to latest version instead, and retry to use it with Compose 🙏 thanks for the insight!

**Comment by mochadwi** [comment]
> will try to update the beagle to latest version instead, and retry to use it with Compose 🙏 thanks for the insight!

upgrading to latest version fixed the issue

**Comment by pandulapeter** [comment]
Wonderful to hear, thanks for the update! In this case I'll go ahead and close this issue.
