### ISSUE TITLE
Firebase distribution check fails - library is using API 24+ drawables?

### ISSUE THREAD

**Issue by DanielNovak** [pandulapeter/beagle#89]
Uploading any app with **minSdkVersion set to API 23** to Firebase App Distribution with `ui-drawer` included will fail due to:

> There's been an error processing your app. Ensure you are uploading a valid APK and try again. If this problem continues, contact Firebase support. Additional information about this error: Failed to run aapt dump badging: AndroidManifest.xml:60: error: ERROR getting 'android:icon' attribute: attribute is not a string value

**This is a misleading error but it basically means that probably some of the modules in beagle is using XML elements that exist only API 24+**.  At least that's my theory. Those gradle modules will then not generate correct layouts for API < 23.  
I think setting `vectorDrawables.useSupportLibrary = true` in each of the problematic build.gradle file could help, but I am not sure (for example `internal-core` uses vector drawables, but doesn't have `vectorDrawables.useSupportLibrary` - this setting must be set in each module separately).

We verified that just removing the library (dependency) from the app fixes the Firebase issue and it confirms that the problem must be inside the beagle library (reverting the commit with beagle also gets rid of the error).

How to repro:
- Create a sample project and add beagle
- set minimum SDK version to API 23
- upload the APK to Firebase App distribution => upload fails with the mentioned error

I had the same problem in another project when we used `android:fillType="evenOdd"` (API 24+) and forgot `vectorDrawables.useSupportLibrary = true`.

**Comment by DanielNovak** [comment]
Here is probably the problem:
https://github.com/pandulapeter/beagle/blob/35b4b33a9758a8da59671a268334e412d161002a/internal-core/src/main/res/drawable/beagle_bg_gradient.xml 

These start/center/end color attributes are API 24+ (https://stackoverflow.com/questions/54979464/vector-drawable-with-gradient-color-not-supporting-below-api-24) and the `internal-cor` build.gradle file doesn't specify `vectorDrawables.useSupportLibrary = true` 

Maybe there are also other layouts like this, but this is the first one I found.

**Comment by DanielNovak** [comment]
We tested the PR #90 locally and it we were able to upload the APK to Firebase after the fix.

**Comment by pandulapeter** [comment]
Hi,

Thanks so much for reporting this issue and also for fixing it! I hope it didin't cause too many headaches.

Give me some time to update all third party dependencies and create a new release that contains this fix. I also have some problems with JitPack recently, builds are taking forever... But I'll close this issue once the new version is available.

**Comment by pandulapeter** [comment]
Your changes are part of [Release 2.6.4](https://github.com/pandulapeter/beagle/releases/tag/2.6.4). Thanks again!
