### ISSUE TITLE
Migrate the project to MavenCentral

### ISSUE THREAD

**Issue by pandulapeter** [pandulapeter/beagle#95]
Jitpack has a number of disadvantages. It would be benefitial for the maturity of the library to be hosted on a MavenCentral instead.

**Comment by captainepoch** [comment]
May I ask what those disadvantages are?

**Comment by pandulapeter** [comment]
The main reason is that apparently there are companies who simply don't allow depending on Jitpack, due to security concerns. Also, it seems like MavenCentral is what most libraries use, and I want to make introducing Beagle to a project as simple and straightforward as possible.

There's a pretty good discussion on the pros / cons [here](https://www.reddit.com/r/androiddev/comments/ni5n9g/releasing_open_source_lib_via_jitpack_vs/).

I also want to improve the way artifacts are created (the build process is very slow now for some reason - probably my fault but not sure) and maybe introduce a separate branch for RC releases. Migrating to a new repository would be a good oportunity to take care of these things.

However, as you can see, this issue has been here for a while. Jitpack is sooo easy to use from the publisher's side, and I'm very much used to it by now.

**Comment by captainepoch** [comment]
I am taking a look at this post (https://proandroiddev.com/publishing-android-libraries-to-mavencentral-in-2021-8ac9975c3e52) to see how this library can be added to Maven Central. It does not seem to be difficult, although it seems to be a bit tedious.

Maybe you could give it a try. I would, but I'd rather prefer not to have any sort of release information related to your library :).

**Comment by pandulapeter** [comment]
Thanks! I'll try to take care of this next week, it's about time

**Comment by pandulapeter** [comment]
I managed to transition to MavenCentral starting with version [2.8.0](https://github.com/pandulapeter/beagle/releases/tag/2.8.0). Please keep in mind that the artifact ID has also changed: instead of `com.pandulapeter.beagle...` it's now `io.pandulapeter.beagle...`.
