### ISSUE TITLE
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#99]
In our case, there's an **in-app** activity (3rd-party library) still not using `Theme.MaterialComponents` yet.

<img width="1099" alt="Screen Shot 2022-04-01 at 6 19 56 AM" src="https://user-images.githubusercontent.com/7057959/161165119-0931a306-4452-47c0-9c5b-6ce3467e3b8f.png">

Is there any possibility to workaround this in beagle?

```
Unable to resume activity {our.company/com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
```
> related issue: https://github.com/CleverTap/clevertap-android-sdk/issues/255

When triggering the in-app activity, the beagle crashed (this only happened in debug mode, fortunately)

**Comment by pandulapeter** [comment]
Beagle won't work for that Activity, but at least you can disable it (for that Activity only) and avoid the crash.

```
Beagle.initialize(
    ...
    behavior = Behavior(
        shouldAddDebugMenu= { activity -> activity !is InAppNotificationActivity }
    ...
    )
)
```

This lambda from above gets invoked in the `onCreate()` of every Activity, and receives that Activity instance as its only argument. It should return a boolean that tells the library whether or not to try and inject itself.

**Comment by mochadwi** [comment]
> 4 days ago

Thank youuu!
